services:
  frontend:
    profiles: ["prod"]

  backend:
    profiles: ["prod"]

  db:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  litellm:
    ports:
      - "4000:4000"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Pgadmin1@}
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: ${PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS:-0}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-net
    restart: unless-stopped

volumes:
  pgadmin_data: