name: Prod Release
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    if: "!endsWith(gitea.ref_name, '-dev')"
    runs-on: ubuntu-latest
    steps:
      - name: Clone/pull then build
        uses: appleboy/ssh-action@v1.2.5
        with:
          username: deploy
          host: ${{ vars.SSH_HOST }}
          port: ${{ vars.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            APP_DIR="/home/deploy/jpdm.dev"
            GITEA_TOKEN="${{ secrets.__GITEA_TOKEN }}"
            GITEA_USERNAME="${{ secrets.__GITEA_USERNAME }}"
            REPO_URL="https://$GITEA_USERNAME:$GITEA_TOKEN@git.jpdm.dev/jp/jpdm.dev.git"
            ENV_CONTENT="${{ secrets.ENV_CONTENT_PROD }}"
            VITE_CONTENT="${{ vars.VITE_CONTENT_PROD }}"

            echo "Starting..."
            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            #check if repo already checked out
            if [ ! -d ".git" ]; then
              echo "Cloning repo..."
              git clone -b master "$REPO_URL" .
              echo "Repo cloned."
            else
              #repo exists
              echo "Pulling latest changes..."
              git fetch origin
              git checkout master
              git reset --hard origin/master
              echo "Code updated."
            fi

            echo "$VITE_CONTENT" > ./frontend/.env
            chmod 600 ./frontend/.env
            chown deploy:deploy ./frontend/.env
            
            echo "$ENV_CONTENT" > .env
            chmod 600 .env
            chown deploy:deploy .env            

            echo "Building images..."
            docker compose build --no-cache
            echo "Build completed"

            echo "Starting up db for migrations..."
            docker compose up -d db

            until docker compose exec db pg_isready -U postgres -d jpdm > /dev/null 2>&1; do
              echo "Waiting for database..."
              sleep 1
            done

            echo "Running database migrations..."
            docker rm -f backend-migrate 2>/dev/null || true
            docker compose run --rm --name backend-migrate backend node dist/migrate.js

            echo "Running database seeding..."
            docker rm -f backend-seed 2>/dev/null || true
            docker compose run --rm --name backend-seed backend node dist/seed.js

            echo "Starting containers..."
            docker compose up -d

            echo "Checking status..."
            sleep 3
            docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

            echo "Deployment completed."
