export const ErrorCode = {
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_MISSING: 'TOKEN_MISSING',
    TOKEN_INVALID: 'TOKEN_INVALID',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    NETWORK_ERROR: 'NETWORK_ERROR',
    AUTH_HEADER_MISSING: 'AUTH_HEADER_MISSING',
    AUTH_HEADER_INVALID: 'AUTH_HEADER_INVALID',
    SERVER_ERROR: 'SERVER_ERROR',
    BOT_DETECTED: 'BOT_DETECTED',
    MISSING_PARAMETER: 'MISSING_PARAMETER',
    LENGTH_TOO_LONG: 'LENGTH_TOO_LONG',
    ALREADY_USED: 'ALREADY_USED',
    MAX_SENT_LIMIT: 'MAX_SENT_LIMIT',
    COOLDOWN: 'COOLDOWN'
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];